### ISSUE TITLE
Red errors are logged

### ISSUE THREAD

**Issue by Proxyer** [Mehni/MoreFactionInteraction#33]
Currently, when the game starts up, a red error "Could not find a type named LanguageWorker_Japanese" is logged. May be a phenomenon only in my environment, but do not you know about the cause of this error? If I remove this Mod from the Mod list, the corresponding error will not be logged.

[Corresponding error log: ]
Could not find a type named LanguageWorker_Japanese
Verse.Log:Error(String, Boolean)
Verse.ParseHelper:FromString(String, Type)
Verse.DirectXmlToObject:ObjectFromXml(XmlNode, Boolean)
System.Reflection.MonoMethod:InternalInvoke(Object, Object[], Exception&)
System.Reflection.MonoMethod:Invoke(Object, BindingFlags, Binder, Object[], CultureInfo)
System.Reflection.MethodBase:Invoke(Object, Object[])
Verse.DirectXmlToObject:ObjectFromXml(XmlNode, Boolean)
Verse.DirectXmlLoader:ItemFromXmlFile(String, Boolean)
Verse.LoadedLanguage:TryLoadMetadataFrom(String)
Verse.LanguageDatabase:LoadLanguageMetadataFrom(DirectoryInfo)
Verse.LanguageDatabase:LoadAllMetadata()
Verse.PlayDataLoader:DoPlayLoad()
Verse.PlayDataLoader:LoadAllPlayData(Boolean)
Verse.Root:<Start>m__1()
Verse.LongEventHandler:RunEventFromAnotherThread(Action)
Verse.LongEventHandler:<UpdateCurrentAsynchronousEvent>m__1()

Change the language to English and delete the Japanese translation file, will get an error. I think it is difficult to think that the translation file is the cause. Thank you.

**Comment by Mehni** [comment]
I'll investigate. I use the LanguageWorker in the AnnualExpo, to give it the "second annual expo" and "third annual expo" instead of "3 annual expo". Maybe I'm using it wrong.

**Comment by Mehni** [comment]
Fixed in 808190047b08b7ed393951186fc0597748d886d9
