### ISSUE TITLE
Small typo

### ISSUE THREAD

**Issue by DrZhivago1** [Mehni/MoreFactionInteraction#38]
https://github.com/Mehni/MoreFactionInteraction/blob/1eff2400c3a53656afad9b4c496dbbb4c3f9f7a6/Defs/Events/AnnualExpoEvents.xml#L65

faire -> fair

**Comment by Mehni** [comment]
What if I rename it as "Renaissance faire"? Or or maybe they've been doing it since the dawn of alchemy, and they only went along with the newfangled "science" on condition they could keep call it a faire? Eh? Eh?

wontfix

**Comment by DrZhivago1** [comment]
I did fail to consider the lore of their world. Excuse me.
